<?php

namespace App;

use App\Scopes\StatusScope;
use Illuminate\Database\Eloquent\Model;

class NotificationType extends Model
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new StatusScope());
    }

    public function stocks()
    {
        return $this->belongsToMany('App\Stock')->withTimestamps();
    }

    public static function updateNotificationTypes($stock, $newNotificationTypes)
    {
        $savedNotificationTypes = $stock->notificationTypes;
        $toDeleteNotificationTypes = $savedNotificationTypes->filter(function ($savedNotificationType) use ($newNotificationTypes) {
            return !$newNotificationTypes->contains('name', $savedNotificationType->name);
        });

        $toAddNotificationTypes = $newNotificationTypes->filter(function ($newNotificationType) use ($savedNotificationTypes) {
            return !$savedNotificationTypes->contains($newNotificationType);
        });

        foreach ($toAddNotificationTypes as $toAddNotificationType) {
            $stock->notificationTypes()->save($toAddNotificationType);
        }

        foreach ($toDeleteNotificationTypes as $toDeleteNotificationType) {
            $stock->notificationTypes()->detach($toDeleteNotificationType->id);
        }
    }

    public function warningConfigs()
    {
        return $this->belongsTo('App\WarningConfig');
    }
}
