<?php

namespace App;

use App\Scopes\StatusScope;
use Illuminate\Database\Eloquent\Model;

class NotificationType extends Model
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new StatusScope());
    }

    public function warningConfigs()
    {
        return $this->belongsToMany('App\WarningConfig')->withTimestamps();
    }
}
